/**:
  ros__parameters:
    #TODO: Figure out all of these values
    spin_velocity: 0
    push_actuator_position: 0
    MAX_PUSH_ACTUATOR_POSITION: 0
    MIN_PUSH_ACTUATOR_POSITION: 0
    MAX_PUSH_ACTUATOR_VELOCITY: 0
    TILT_ACTUATOR_SPEED: 0
    TILT_MOTOR_ID: 0
    PUSH_MOTOR_ID: 0
    SPIN_MOTOR_ID: 0